name: Automated review
 
on: [push]
 
jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: npm updates
        run: npm install

      #- name: Run prettier check
        #run: npm run check
  build-container:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v4
      - run: npm test
 
