name: Automated review
 
on: [push]
 
jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: npm updates
        run: npm install

      #- name: Run prettier check
        #run: npm run check
  build-container:
    needs: quality-check
    runs-on: ubuntu-latest
    env:
      # TAG_DYNAMIC: main
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}
    steps:
      - name: Build docker image
        run: |
          docker build . \
          --file Dockerfile  \
          --tag angular-todos-app:$TAG_DYNAMIC \
          --tag angular-todos-app:latest

      #- name: wohin docker image
 
